# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='blogpost',
                name='content',
                field=models.CharField(default=datetime.datetime(2015, 12, 27, 16, 39, 8, 22661, tzinfo=utc),
                                       max_length=2000),
                preserve_default=False,
        ),
    ]
